CREATE DATABASE TP1B
GO
USE TP1B
GO

CREATE TABLE CARRERAS(
	CODIGO_CARRERA INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	NRO_RESOLUCION VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MATERIAS (
	CODIGO_MATERIA INT NOT NULL PRIMARY KEY,
	CODIGO_CARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS(CODIGO_CARRERA),
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE DOCENTES (
	DNI INT NOT NULL UNIQUE,
	LEGAJO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	FECHA_NAC DATE NOT NULL
)
GO
CREATE TABLE CARGO_DOCENTES(
	ID_CARGO SMALLINT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE PLANTA_DOCENTES(
	ANIO DATE NOT NULL, 
	LEGAJO INT NOT NULL FOREIGN KEY REFERENCES DOCENTES (LEGAJO),
	MATERIA INT NOT NULL FOREIGN KEY REFERENCES MATERIAS(CODIGO_MATERIA),
	CARGO SMALLINT NOT NULL FOREIGN KEY REFERENCES CARGO_DOCENTES(ID_CARGO)
	PRIMARY KEY(LEGAJO, MATERIA, ANIO)
)